server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ocean?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #连接池最大连接数
        max-active: 8
        #最大阻塞等待时间，负值表示没有限制
        max-wait: -1
        #最大空闲连接
        max-idle: 500
        #最小空闲连接
        min-idle: 0
    lettuce:
      shutdown-timeout: 0


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

logging:
  level:
    com.example.demo.mapper: debug
